.TH "Hello World"
.SH "Saying hello to the world"
.PP
This is how you say hello.


.\" .TH	Title Header
.\" ..SH	Section Header
.\" ..B	Bold
.\" ..I	Italic
.\" ..TP	Tagged paragraph (indented list)
.\" ..PP	Paragraph
.\" ..RS/.RE	Relative indent
.\" ..nf/.fi	Disable/Enable filling (for code blocks)

