.Dd July 2025
.Dt "Tmothy Cooper"
.Os Tim Cooper Resume
.\".Sh NAME
.\".Nm Tim Cooper
.Sh "Tim Cooper"
.Nd Reliability Engineer, Software Engineer, System Administrator Reliability Engineer, Software Development. Enterprise Platforms Scripting and Markup: Power-shell, bash, Python, C/C++, Java, HTML, Project Tracking,Compliance Audits, Hardware and Licensing

.Sh Contact
.Bl -tag -compact -width "GitHub:"
.It Em Email:
.Aq timcooperlabs@gmail.com
.It Em Phone:
.Aq +1 619-227-8478
.Pq 1537 Tuley Street Dallas TX, 75104
.It Em GitHub:
.Aq github.com/xmorg ,
.Aq github.com/alsoxmorg
.El

.Sh SKILLS
.Bl -tag -compact -width
.It Sy Languages
 bash, Python3, C/C++, Java, HTML, json
.It Sy Tools
Ansible, Docker, Podman, Git, systemd, tmux, ssh
.It Sy Platforms
Debian, RHEL, Ubuntu, Alpine, FreeBSD
.It Sy Infra
NGINX, iptables, WireGuard, fail2ban
.El

.Sh EXPERIENCE
.Bl -tag -width Ds
.It Aurora Innovation - Vehicle Reliability Engineer
December 1, 2021 - present
- Bug tracking, Triaging and troubleshooting from autonomous Trucking Systems.
- Software provisioning of Ubuntu, and QNX and AVOS on vehicle computers.
- Technical Document writing on github, Terminal App, Python and internal processes

.It IT Service Desk, Dimont, Dallas TX
April 2017- September 2021
- Microsoft Exchange 2016 and 365, Azure, Intune, Active Directory
- SharePoint, Landesk, ServiceNow, ManageEngine, Coldfusion
- Release Engineer, Agile testing and production cycle
- VPN and 2FA troubleshooting, DUO Mobile, and Microsoft Authenticator

.It IT Service Desk, Dimont, Dallas TX
October 2013 - March 2017
- Email migration, Exchange Journaling
- Trained and lead a team to successfully implement email compliace for advisors.
- PC tech support, Browsers, Networks, Microsoft Exchange, POP/IMAP

.El

.Sh PROJECTS
.Bl -tag -width Ds
.It Sy ffpirateview
https://github.com/xmorg
- Expansion of the Farbfeld suckless tools for lossless images.
- Created new image format "1fpirate" designed for drawings and document scans
- converter tools to convert files to and fron png and farbfeld.
.It Sy myebookshellread
https://github.com/xmorg/myebookshellread
- myebookshellread - a lightweight shell based ebook reader which uses espeak to read lines aloud, and keeps track wtih bookmark files.
.It Sy Horror Tactics - Java Test game
https://github.com/xmorg/horrorTactics
- 2D isometric turned-based game written to showcase java and the tiled map editor.
.It Sy LeTown Builder
https://github.com/xmorg/letownbuilder
- Lua "LOVE" based game written to release on the play store, and PC.
- Proof of concept Indie game.
.El

.Sh EDUCATION
.Bl -tag -width Ds
.It B.S. in Computer Science
Southwestern College, Chula Vista, CA
.El

.Sh REFERENCES
Available upon request.
